### ISSUE TITLE
Whisper - Sending message before request is accepted

### ISSUE THREAD

**Issue by JorisBassle** [threefoldtech/freeflow_twin_main#643]
How to reproduce:
- Send request to user
- Send message to that user
- Accept the request

The message does not appear in his chat unless you refresh the page.

**Comment by ken-de-moor** [comment]
Still happened for me.

Refresh fixed it indeed.

**Comment by JorisBassle** [comment]
Was not yet pushed to staging

**Comment by ken-de-moor** [comment]
Still happens

![image](https://user-images.githubusercontent.com/59569757/193860722-00e2076c-e090-4575-b202-bb552c30ebd6.png)

Moved to 1.7

**Comment by JorisBassle** [comment]
The messages apear if you send more than 1 message before the request has been accepted.
If you send a request and then a message quickly after the other user doesn't get a request at all.
