### ISSUE TITLE
[MOBILE][WHISPER] Adding user doesn't use full height.

### ISSUE THREAD

**Issue by JorisBassle** [threefoldtech/freeflow_twin_main#718]
some information is cut off while there is still enough room
![image](https://user-images.githubusercontent.com/36887810/184890524-92e013a7-736f-453c-960f-c72d59580211.png)

**Comment by ken-de-moor** [comment]
Still happens but minor issue, moving to 1.7

![image](https://user-images.githubusercontent.com/59569757/193858804-e365ad43-7272-48dd-8a4e-bac8d0672871.png)
