### ISSUE TITLE
deploy on the threefold grid

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/freeflow_twin_main#724]
Deployment of twin_aydo seems to be requiring a virtual machine that runs the main service "the spawner", and it will spawn other containers and join them in a docker network

to prove the concept:
you can deploy a VM using [typescript client](https://library.threefold.me/info/manual/#/manual3_iac/grid3_javascript/manual__grid3_javascript_home)or [weblets](https://library.threefold.me/info/manual/#/manual__weblets_home) or [terraform](https://library.threefold.me/info/manual/#/manual3_iac/grid3_terraform/manual__grid3_terraform_home)

The typescript client has tons of examples, so should be really easy to spawn an ubuntu VM of the project install docker and docker compose and test the flow
 
## a more ideal deployment
- prepare image for the spawner
- prepare image for the service that gets spawned
- convert both to flists
- deploy using the typescript client
- ignore the dependence on docker network, you can use yggdrassil for the communication already.
- you can use the farms gateways for the domains, or dynamically create domains through service like godaddy or name.com

**Comment by LennertDefauw1** [comment]
Update:

Been able to deploy 2 chatcontainers on seperate nodes / VM's. Been able to communicate with each other (HTTP only). 

Next step is to support SSL. For that, we need a certificate and DNS. @xmonader will provide a third party service so we can easily ask certificates and provide them for that node. @xmonader will contact us back when this service is up and running.

Last step is to convert everything to an flist with a customized init script, so no extra workload of deploying a full ubuntu VM is needed.

**Comment by LennertDefauw1** [comment]
Update:

Able to deploy a FreeFlow container as flist via the typescript client. Over https due usage of the wildcard dns from the gateway of freefarm. 

Arguments that will be needed to deploy a container:

WALLET_SECRET (for billing of the running containers)
SSH_KEY (for access to his container)
3BOT NAME (for DNS gateway)


When deploy is success, you can access your FreeFlow container by going to eg. https://lennertapp2.gent01.grid.tf/

On this page, you will need to authenticate with the 2FA of ThreeFold Connect, if successfull you will get redirected to your own FreeFlow container!


There is still one issue: Redis container sometimes get wiped due appendonly and save (see https://stackoverflow.com/questions/50264694/my-redis-auto-generated-keys)
