### ISSUE TITLE
[WHISPER] Spam clicking 'add user' adds the same user multiple times

### ISSUE THREAD

**Issue by JorisBassle** [threefoldtech/freeflow_twin_main#807]
If it takes to long to add the user you can click on the user for multiple times. This shows the user multiple times in the members list.

![image](https://user-images.githubusercontent.com/36887810/195572620-f5c2605a-2d96-4309-904d-daa2d82d7353.png)

**Comment by ken-de-moor** [comment]
![image](https://user-images.githubusercontent.com/59569757/202474875-fc980b10-5a89-4daf-a589-dc5564ac6ab9.png)
