### ISSUE TITLE
[APP]  Android - Context menu on chats doesn't work.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflow_twin_main#939]
- Hold click on a chat in Whisper
- Try to delete or do any other action

=> The click on the action doesn't do anything.

**Comment by JorisBassle** [comment]
Can this be done like this @Baertie ?
https://github.com/threefoldtech/freeflow_twin_main/issues/988#issuecomment-1415973010

**Comment by Baertie** [comment]
It can be done like this
