### ISSUE TITLE
[DASHBOARD] Creating post with unsupported files gives wrong error

### ISSUE THREAD

**Issue by JorisBassle** [threefoldtech/freeflow_twin_main#956]
It says 'no specials characters allowed' while it should be 'file not supported for posts'

**Comment by LennertDefauw1** [comment]
Any idea what filetype this was?

![image](https://user-images.githubusercontent.com/43674202/215740799-0de09264-3567-4a97-b2d7-c6e81af2398b.png)



Tried .js, .txt, .pdf and everything worked as expected
