### ISSUE TITLE
[WHISPER] '.txt' or other simple files don't show up on 'files' list of the chat

### ISSUE THREAD

**Issue by JorisBassle** [threefoldtech/freeflow_twin_main#965]
![image](https://user-images.githubusercontent.com/36887810/215154008-66c629c2-4671-4186-9f47-293f0c513065.png)

**Comment by ken-de-moor** [comment]
Fix in 1.8 if fix is easy, move to 1.9 if fix takes a lot more work.

**Comment by LennertDefauw1** [comment]
![image](https://user-images.githubusercontent.com/43674202/215740105-ea5b4661-4e7a-4ad2-be18-fda94931e8ce.png)

**Comment by LennertDefauw1** [comment]
Seems to work on my side, got some more details on how to reproduce?
